development: &default
  domain: "http://127.0.0.1:3000"
  domain_css: "http://127.0.0.1:3000/stylesheets"
  domain_js: "http://127.0.0.1:3000/javascripts"
  session_secret: "1234567890abcdefghigklmnsdfewiruewpo-12i0.dsas90dojidco2"
  site_title: "精品导购"
  site_description: "做专业的导购网站"
  site_keywords: "导购"
  site_error_info: "服务器忙，请稍候重试！"
  
production:
  <<: *default
  domain: "http://www.helloqidi.com"
  domain_css: "http://www.helloqidi.com/stylesheets"
  domain_js: "http://www.helloqidi.com/javascripts"

test: 
  <<: *default
  domain: "http://www.helloqidi.com"
  domain_css: "http://www.helloqidi.com/stylesheets"
  domain_js: "http://www.helloqidi.com/javascripts"
