development: &default
  domain: "http://127.0.0.1:3000"
  domain_css: "http://127.0.0.1:3000/stylesheets"
  domain_js: "http://127.0.0.1:3000/javascripts"
  session_secret: "1234567890abcdefghigklmnsdfewiruewpo-12i0.dsas90dojidco2"
  site_title: "精品导购 - 专业的导购网站,最好的网购产品推荐"
  site_description: "精品导购是一个中立的为广大网友提供高性价比网购产品的推荐网站.我们每天推荐最新最全最优性价比的网购优惠信息,海淘特价信息。如果您发现了好的优惠打折信息，也可通过我们与更多网友分享。"
  site_keywords: "导购 比价 网购 产品推荐"
  site_error_info: "服务器忙，请稍候重试！"
  #其他类别,用于抓取数据时的类别存储
  category_other_id: 1
  #默认一个用户,用于抓取数据时的用户信息存储
  default_user_id: 2
  qiniu_access_key: "QPqYEAMobxb9yJApcclkXjDm_dCVR6CcDFI6y0Pa"
  qiniu_secret_key: "JhVi8FUeNYonv_TjaUU6pjbN3M880S3jNGrRZSlb"
  qiniu_bucket: "testhelloqidi"
  qiniu_bucket_domain: "testhelloqidi.u.qiniudn.com"
  duoshuo_short_name: "helloqidi"
  duoshuo_secret: "ff8d04c295dc21e44232d51fda900878"
  
production:
  <<: *default
  domain: "http://www.helloqidi.com"
  domain_css: "http://static.helloqidi.com/stylesheets"
  domain_js: "http://static.helloqidi.com/javascripts"
  category_other_id: 97
  default_user_id: 1
  qiniu_access_key: "QPqYEAMobxb9yJApcclkXjDm_dCVR6CcDFI6y0Pa"
  qiniu_secret_key: "JhVi8FUeNYonv_TjaUU6pjbN3M880S3jNGrRZSlb"
  qiniu_bucket: "helloqidi"
  qiniu_bucket_domain: "helloqidi.u.qiniudn.com"

test: 
  <<: *default
  domain: "http://www.helloqidi.com"
  domain_css: "http://www.helloqidi.com/stylesheets"
  domain_js: "http://www.helloqidi.com/javascripts"
